services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.9
    ports:
      - 8888:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL:${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD:${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped
    env_file:
      - .env
networks:
  kestra_default:
    external: true
volumes:
  pgadmin-data:
    driver: local
