all:
  children:
    server:
      hosts:
        armbian:
          ansible_host: 10.10.2.2
          ansible_user: fatih
          ansible_ssh_private_key_file: /home/fatih/.ssh/fatih
          ansible_become_password: ${ANSIBLE_BECOME_PASSWORD}
        proxmox:
          ansible_host: 10.10.2.3
          ansible_user: fatih
          ansible_ssh_private_key_file: /home/fatih/.ssh/fatih
          ansible_become_password: ${ANSIBLE_BECOME_PASSWORD}
    vm:
      hosts:
        sage:
          ansible_host: 10.10.3.25
          ansible_user: fatih
          ansible_ssh_private_key_file: /home/fatih/.ssh/fatih
          ansible_become_password: ${ANSIBLE_BECOME_PASSWORD}