services:
    adguard:
        container_name: adguard
        image: adguard/adguardhome
        ports:
         - 53:53/tcp
         - 53:53/udp
        volumes:
         - ./workdir:/opt/adguardhome/work
         - ./confdir:/opt/adguardhome/conf
        restart: always
        networks:
         proxy:
           ipv4_address: 172.21.0.15
         pdns:
           ipv4_address: 172.20.0.15
        labels:
         - traefik.enable=true
         - traefik.docker.network=proxy
         - traefik.http.routers.adguard.rule=Host(`adguard.srv-prod-1.local.latansatech.my.id`)
         - traefik.http.routers.adguard.entrypoints=https
         - traefik.http.routers.adguard.tls=true
         - traefik.http.routers.adguard.tls.certresolver=cloudflare
         - traefik.http.services.adguard.loadbalancer.server.port=80
            
         - traefik.tcp.routers.adguard-tls.rule=HostSNI(`adguard.srv-prod-1.local.latansatech.my.id`)
         - traefik.tcp.routers.adguard-tls.entrypoints=dot
         - traefik.tcp.routers.adguard-tls.tls=true
         - traefik.tcp.routers.adguard-tls.tls.certresolver=cloudflare
         - traefik.tcp.routers.adguard-tls.service=adguard-tls
         - traefik.tcp.services.adguard-tls.loadbalancer.server.port=53

networks:
  proxy:
    external: true
  pdns:
    external: true