services:
  semaphore:
    container_name: semaphore
    image: semaphoreui/semaphore:v2.10.22
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_DIALECT= ${SEMAPHORE_DB_DIALECT}
      - SEMAPHORE_DB_HOST= ${SEMAPHORE_DB_HOST}
      - SEMAPHORE_DB_NAME= ${SEMAPHORE_DB_NAME}
      - SEMAPHORE_DB_USER= ${SEMAPHORE_DB_USER}
      - SEMAPHORE_DB_PASS= ${SEMAPHORE_DB_PASS}
      - SEMAPHORE_ADMIN= ${SEMAPHORE_ADMIN}
      - SEMAPHORE_ADMIN_PASSWORD= ${SEMAPHORE_ADMIN_PASSWORD}
      - SEMAPHORE_ADMIN_NAME= ${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL= ${SEMAPHORE_ADMIN_EMAIL}