services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    env_file: .env
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - ./config:/app/config
      - ./config/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`homepage.srv-prod-1.local.latansatech.my.id`)
      - traefik.http.routers.homepage.entrypoints=https
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=cloudflare
      - traefik.http.services.homepage.loadbalancer.server.port=3000

networks:
  proxy:
    external: true