services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:1.23.16
    restart: always
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.rule=Host(`uptimekuma.srv-prod-1.local.latansatech.my.id`)
      - traefik.http.routers.uptimekuma.entrypoints=https
      - traefik.http.routers.uptimekuma.tls=true
      - traefik.http.routers.uptimekuma.tls.certresolver=cloudflare
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001

networks:
  proxy:
    external: true

volumes:
  uptime-kuma: