services:
  mariadb:
    image: mariadb:11-ubi
    container_name: powerdns-mysql-mariadb
    networks:
      pdns:
        aliases:
          - db
          - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always

  pdns-mysql-master:
    image: pschiffe/pdns-mysql:latest
    container_name: powerdns-mysql-master
    hostname: pdns
    networks:
      pdns:
        ipv4_address: 172.20.0.20
        aliases:
          - pdns
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_gmysql_password=${PDNS_GMYSQL_PASSWORD}
      - PDNS_gmysql_dnssec=yes
      - PDNS_primary=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_allow_from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_axfr_ips=127.0.0.1
      - PDNS_only_notify=0.0.0.0
    depends_on:
      - mariadb
    restart: always

  pdns-admin-mysql:
    image: pschiffe/pdns-admin
    container_name: powerdns-mysql-admin
    networks:
      proxy:
      pdns:
        aliases:
          - pdns-admin
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PDNS_ADMIN_SQLA_DB_PASSWORD=${PDNS_ADMIN_SQLA_DB_PASSWORD}
      - PDNS_VERSION=4.8
      - PDNS_API_KEY=${PDNS_API_KEY}
    depends_on:
      - mariadb
      - pdns-mysql-master
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.pdns.rule=Host(`powerdns.srv-prod-1.local.latansatech.my.id`)
      - traefik.http.routers.pdns.entrypoints=https
      - traefik.http.routers.pdns.tls=true
      - traefik.http.routers.pdns.tls.certresolver=cloudflare
      - traefik.http.services.pdns.loadbalancer.server.port=8080
    restart: always

networks:
  pdns:
    external: true
  proxy:
    external: true

volumes:
  mariadb: